[package]
name = "dupchecker"
version = "0.5.0"
edition = "2021"
authors = ["Safort <a.asafort@gmail.com>"]
repository = "https://github.com/Safort/dupchecker"
description = "Library, which helps to check files for duplicates"
license = "MIT"


[dependencies]
